### ISSUE TITLE
Old School Ispiration

### ISSUE THREAD

**Issue by gkedge** [mattzeunert/fromjs#3]
Year's ago, I did this very thing for Java's thick client package, Swing. I called it [GlassTools](http://glasstools.kedges.com/).

For any person tossed into the middle of large SPA project or triaging defects on an SPA that they didn't develop, a procject list this will be extreemly valuable.

Best of luck on your efforts.

**Comment by mattzeunert** [comment]
Nice, that looks cool! Interesting to see other tools that help make the link between UI and code.
